steps:
- name: "gcr.io/sacred-atom-384814/gcpdevops"
  args: [ 'build' , '-t' , 'gcr.io/$PROJECT_ID/gcpdevops', '.'] 
- name: "gcr.io/sacred-atom-384814/gcpdevops"
  args: [ 'push' , 'gcr.io/$PROJECT_ID/gcpdevops']
- name: "gcr.io/sacred-atom-384814/gcpdevops"
  args:
  - run
  - --filename=dep.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --location=us-central1-c
  - --cluster=devops-gcp
  - --namespace=gcp-devops-prod
